# Numpy And Pandas Exercises

## 1. Exercuting the Following Instructions Using the Various Functions Under Numerical Python 

### a. Creating a 2 by 3 matrix from 1 to 6

In [4]:
# 2 by 3 matrix from 1-6
import numpy as np
Matrix_A = np.array([[1,2,3],[4,5,6]])
print(Matrix_A)

[[1 2 3]
 [4 5 6]]


In [5]:
#multiplying matrix_A by 2
print(Matrix_A*2)

[[ 2  4  6]
 [ 8 10 12]]


 ### b.Creating a 3 by 3 Identity Matrix

In [6]:
# 3 by 3 identity matrix
Matrix_B = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(Matrix_B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### C. creating a 1-D array from 0 to 27

In [7]:
#1-D array from 0-27
arry1 = np.arange(27)
print(arry1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [8]:
# converting the 1-D array to a 3-D array
arry2 = arry1.reshape(3,3,3)
print(arry2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### d.creating a 2-D array containing 1 to 6 and 7 to 12 and stcking the two arrays vertically and horizontally

In [9]:
#2-D array from 1-7
arry_A = np.array([[1, 2 , 3,], [4, 5, 6]])
print(arry_A)

[[1 2 3]
 [4 5 6]]


In [10]:
# 2-D array from 7-12
arry_B = np.array([[7, 8, 9], [10, 11, 12]])
print(arry_B)

[[ 7  8  9]
 [10 11 12]]


In [11]:
# verticall stacking arry_A and arry_B
v_stack = np.vstack((arry_A, arry_B))
print(v_stack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
#horrizontal stacking arry_A and arry_B
h_stack = np.hstack((arry_A, arry_B))
print(h_stack)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### e. from 0 to 100 sequence with equally spacing of 5

In [60]:
# from 0-100 sequence with 5 gaps spacing
for i in range(0, 101, 5):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100


## 2. Some Pandas associated Functions in python

###  a. Dataframe of names of five students

In [18]:
import pandas as pd

In [19]:
# generating the list of students
student_names = ['John Kumah', 'Sarah Amafroh', 'David Atisu', 'Emily Katamani', 'Corban Manfari']

In [20]:
#creating the dataframe of the list of students
students = pd.DataFrame(student_names, columns=['Name'])

In [21]:
#printing the dataframe
print(students)

             Name
0      John Kumah
1   Sarah Amafroh
2     David Atisu
3  Emily Katamani
4  Corban Manfari


   ### b. Ghana Premier League Teams and their goals scored in their last five maches

In [22]:
import pandas as pd

In [23]:
#generating the names of teams in Ghana
team_names = ['Accra Hearts of Oak', 'Asante Kotoko', 'Ashanti Gold SC', 'Aduana Stars', 'Medeama SC', 'Ebusua Dwarfs', 'WAFA SC', 'Elmina Sharks', 'Legon Cities FC', 'Bechem United', 'Berekum Chelsea', 'King Faisal Babes', 'Inter Allies FC', 'Great Olympics', 'Liberty Professionals', 'Karela United']


In [24]:
# goals scored, conceeded and points of the teams
goals_dict = {
    'Accra Hearts of Oak': [2, 3, 1, 1, 4],
    'Asante Kotoko': [1, 2, 0, 3, 2],
    'Ashanti Gold SC': [2, 0, 1, 2, 0],
    'Aduana Stars': [1, 2, 0, 0, 3],
    'Medeama SC': [1, 0, 1, 2, 0],
    'Ebusua Dwarfs': [0, 2, 0, 1, 1],
    'WAFA SC': [3, 1, 2, 3, 0],
    'Elmina Sharks': [1, 2, 1, 1, 0],
    'Legon Cities FC': [0, 1, 1, 0, 0],
    'Bechem United': [1, 0, 0, 2, 2],
    'Berekum Chelsea': [2, 1, 2, 3, 1],
    'King Faisal Babes': [0, 1, 1, 1, 0],
    'Inter Allies FC': [2, 3, 0, 1, 0],
    'Great Olympics': [1, 1, 1, 0, 0],
    'Liberty Professionals': [0, 2, 0, 1, 2],
    'Karela United': [2, 2, 1, 1, 1]
}

In [25]:
#generating the dataframes
teams = pd.DataFrame.from_dict(goals_dict, orient='index', columns=['match1', 'match2', 'match3', 'match4', 'match5'])


In [26]:
teams['team_name'] = team_names

In [27]:
teams.set_index('team_name', inplace=True)

In [28]:
print(teams)

                       match1  match2  match3  match4  match5
team_name                                                    
Accra Hearts of Oak         2       3       1       1       4
Asante Kotoko               1       2       0       3       2
Ashanti Gold SC             2       0       1       2       0
Aduana Stars                1       2       0       0       3
Medeama SC                  1       0       1       2       0
Ebusua Dwarfs               0       2       0       1       1
WAFA SC                     3       1       2       3       0
Elmina Sharks               1       2       1       1       0
Legon Cities FC             0       1       1       0       0
Bechem United               1       0       0       2       2
Berekum Chelsea             2       1       2       3       1
King Faisal Babes           0       1       1       1       0
Inter Allies FC             2       3       0       1       0
Great Olympics              1       1       1       0       0
Liberty 

### C. a DataFrame  of West African countries using a dictionary, their names, capitals, and populations of the country

In [51]:
#The names of West African Countries, their capital towns and their populations
data = {'Country': ['Nigeria', 'Ghana', 'Cote d\'Ivoire', 'Liberia', 'Sierra Leone', 'Guinea', 'Mali', 'Senegal', 'Burkina Faso', 'The Gambia'],
        'Capital': ['Abuja', 'Accra', 'Yamoussoukro', 'Monrovia', 'Freetown', 'Conakry', 'Bamako', 'Dakar', 'Ouagadougou', 'Banjul'],
        'Population': [206139587, 31072940, 26378274, 5057681, 7976983, 13132795, 20250834, 16296364, 20903278, 2347706]}


In [30]:
#the dataframe of West African Countries
countries = pd.DataFrame(data)

In [31]:
print(countries)

         Country       Capital  Population
0        Nigeria         Abuja   206139587
1          Ghana         Accra    31072940
2  Cote d'Ivoire  Yamoussoukro    26378274
3        Liberia      Monrovia     5057681
4   Sierra Leone      Freetown     7976983
5         Guinea       Conakry    13132795
6           Mali        Bamako    20250834
7        Senegal         Dakar    16296364
8   Burkina Faso   Ouagadougou    20903278
9     The Gambia        Banjul     2347706


### d. A programme capturing  the provided dataset in python.

In [36]:
#i.creating the given table
#names of the teams and the goals 
import pandas as pd
Sno = [1,2,3,4,5,6,7]
team = ['Accra Hearts of Oak', 'Asante Kotoko', 'Ebusua Duafs', 'Sekondi Hassacas', 'Okwahu United', 'Tano Bofoakwa', 'BA United']
gf = [120,90,90,80,78,70,71]
ga = [35,55,60,43,39,50,55]
pts = [80,60,60,55,53,49,44]

In [42]:
# assigning the headings to the table
teams_standing={'SNO':Sno,'Teams':team,'GF':gf,'GA':ga, 'PTS':pts}

In [41]:
#creating the dataframe
league_table = pd.DataFrame(teams_standing)
league_table

SNO                Teams   GF  GA  PTS
0    1  Accra Hearts of Oak  120  35   80
1    2        Asante Kotoko   90  55   60
2    3         Ebusua Duafs   90  60   60
3    4     Sekondi Hassacas   80  43   55
4    5        Okwahu United   78  39   53
5    6        Tano Bofoakwa   70  50   49
6    7            BA United   71  55   44

In [47]:
#ii.a.teams that conceeded more than 30 goals
league_table[league_table['GA']>30]

SNO                Teams   GF  GA  PTS
0    1  Accra Hearts of Oak  120  35   80
1    2        Asante Kotoko   90  55   60
2    3         Ebusua Duafs   90  60   60
3    4     Sekondi Hassacas   80  43   55
4    5        Okwahu United   78  39   53
5    6        Tano Bofoakwa   70  50   49
6    7            BA United   71  55   44

In [49]:
#ii.b. tteams that conceeded less than 80 goals
league_table[league_table['GF']<80]

SNO          Teams  GF  GA  PTS
4    5  Okwahu United  78  39   53
5    6  Tano Bofoakwa  70  50   49
6    7      BA United  71  55   44

In [50]:
#ii.c. teams that had less than 60 point
league_table[league_table['PTS']<60]

SNO             Teams  GF  GA  PTS
3    4  Sekondi Hassacas  80  43   55
4    5     Okwahu United  78  39   53
5    6     Tano Bofoakwa  70  50   49
6    7         BA United  71  55   44